### ISSUE TITLE
Decide on primary language

### ISSUE THREAD

**Issue by sellnat77** [CECS343Project/Farm#1]
Current options
- Web app
  -  PHP, Ruby, Javascript, CSS, HTML, Python, C#
- Android app
  - Java, XML, PHP
- Desktop app
  - Java, PHP

These are the options off the top of my head, we can use this to discuss which method we want to use outside of class

**Comment by sellnat77** [comment]
Ive done some research and found three possibilities to get what we need:
- [Google GWT](http://www.gwtproject.org/)
  - Small syntax differences - write and compile the java code, then (long compile time) the GWT takes the code and converts it to javascript and web elements to work on all browsers and mobile
  - Has an eclipse plugin that includes highlighting
  - Developed by Google 
  - Seems to allow unlimited(?) concurrent users
- [Ajax Swing](http://www.creamtec.com/products/ajaxswing/)
  - Free version not as fully featured
  - Takes java code and converts to ajax etc
    *Similar to GWT
  - Only allows 5 concurrent users at one time, otherwise displays error
    - Not best for our case
- [Web on Swing](http://webonswing.sourceforge.net/)
  - Old tech. 
  - Completely free
  - Most documentation uses Apache tomcat server which we need 
  - Not many theming options I think

### Ultimately, I think if we learn GWT and swing it will make our lives easier

**Comment by sellnat77** [comment]
I started a REALLY basic example of the farm ui with gwt, as far as creating ui, this is really easy, and styling is even easier. This has no functionality but to create it took me a good 20 minutes? [Link to my tests](http://github.com/sellnat77/GWTTests)

![image](https://cloud.githubusercontent.com/assets/3691245/5890027/ffb6b20e-a3f9-11e4-8954-e73d3d3cc1dd.png)

**Comment by sellnat77** [comment]
We are all set on GWT 
@CECS343Project/owners Comment just so i know you know how to check these and are getting the emails

Last person to comment - Close this issue to get used to the functionality

**Comment by djblanc360** [comment]
yeah i am
