### ISSUE TITLE
Create Favicon

### ISSUE THREAD

**Issue by sellnat77** [CECS343Project/Farm#32]
Create 16x16 logo to be displayed in tab bar

**Comment by djblanc360** [comment]
![pill bug](https://cloud.githubusercontent.com/assets/2713016/6205262/5e37fe76-b51d-11e4-8f5b-e086248a6c07.png)

**Comment by djblanc360** [comment]
possible design for logo and for tab bar. still needs a bit of tweaking

**Comment by nfulinarajr** [comment]
![pillbug](https://cloud.githubusercontent.com/assets/10622928/6252105/c25e5f40-b74c-11e4-8cb5-fcef4a24502f.png)

My current idea. It's clean and simple. I like your idea as well but I am unsure about the antennae. I thought about it too but I feel it deviates a little too much?

**Comment by djblanc360** [comment]
it doesnt look like a rolly polly tho haha

**Comment by sellnat77** [comment]
@nfulinarajr Can you make that into a smaller size as well, both 16x16px and 32x32px
