### ISSUE TITLE
Agree on Mission Objective

### ISSUE THREAD

**Issue by sellnat77** [CECS343Project/Farm#35]
Post your comments on whether or not you agree on the following for our application
## The Goal

The Pill Bug database will provide subscription service where the data maintains medicine information for doctor and pharmacist to use, also allow patients to get his or her medication with strict and secure transactions.
## Mission Objective

---
### Doctor
- Add prescription for patient
- Input patient record information
- Maintain patients record information
- Remove prescription for patient
- Renew prescription for patient
- **Do Not Delete patient record**
- Track prescription status
### Pharmacist
- Add patients to database
- Fill in prescription
- Refill Prescription
- Add prescription for the patient who brings in a paper from the doctor
- Add billing/insurance information
- Prepare prescription for walk-in filled/refilled
- prepare prescription for appointment filled/refilled
- prepare precription for shipping filled/refilled
# Post your comments, whether you agree or disagree

@nfulinarajr @djblanc360 @farmproject

**Comment by nfulinarajr** [comment]
The Goal:
    The Pill Bug web application will provide a subscription-based service, utilizing a robust back-end database, maintaining medical data for doctors and pharmacists to dynamically search, add and maintain patient information. Pill Bug offers a more efficient and faster solution for prescription distribution and through strict and secure transactions; patients will be able to receive his or her medication.

Doctor:
• Add patient to database
• Add patient record information
• Search patient within database
• Remove prescription for patient
• Renew prescription for patient
• Send prescription to pharmacy
• Track prescription status
• Maintain patient record

Pharmacist:
• Refill prescription
• Prepare prescription
• Fill digital and paper prescription
• Add patient, billing and insurance information to database

Ambitious:
• Prepare prescription for walk-in filled and refilled
• Prepare prescription for shipping filled and refilled
• Prepare prescription for appointment filled and refilled

I'm not entirely sure how you wanted to implement this. Would it be hard? I'm thinking for the scope of the project, given the time we have, maybe an general "Prepare prescription" and add more functionality if we have time? I could be over-thinking the original idea but that is my only real critique besides rewording 'Project Goal' and condensing the 'Mission Objective'.

**Comment by sellnat77** [comment]
I agree with Napoleon, for the sake of the project i think all we need to do is be able to...
- Prepare a prescription
- Add a patient with all their information
- And be able to send that prescription to a pharmacy running the same program

Of course there's more intricacies but you guys have them covered in your bullets 
As far as the filling written prescriptions, thats something that is very important, but for the class we should just assume its a perfect world and everyone is using our software because 

## We are the best.

**Comment by sellnat77** [comment]
I think you've got what you need to fully design this thing so i am going to close this issue
