### ISSUE TITLE
Create GUI for everything

### ISSUE THREAD

**Issue by djblanc360** [CECS343Project/Farm#40]

**Comment by sellnat77** [comment]
Add main container panel to add 4 sub classes to 
Add the four sub classes for viewing patient information
Add sub classes to main container using horiz/vert panels

**Comment by sellnat77** [comment]
@djblanc360 Will create the base classes with the necessary boxes/buttons/labels etc
@nfulinarajr Will style the classes and ensure the flow between panels is functional
