### ISSUE TITLE
Establish database relationships

### ISSUE THREAD

**Issue by sellnat77** [CECS343Project/Farm#5]
Decide on what is needed for this app.

@farmproject will handle it in the end but we are all responsible for at least contributing

**Comment by sellnat77** [comment]
Patient table
Doctor table
Application table "Farm table?"
Prescription table
Pharmacy table
thats all i can think of, not sure what else to include

**Comment by farmproject** [comment]
Here are the stored variable inside the databases

username
password

patience
first name
last name
middle name
suffix
address
email
home phone
cell phone
date of birth
policy number
policty issuer
policy status

Doctor :
first name
last name
suffix
middle name
email
license number
office address
office phone number
date of birth
Specialty

prescription
hospital/clinic/dentist
date
prescribed medicine
prescribed dose
prescribed date

medication
medicatoin name
drug allergies

medication list
dosage
times per (ask intake frequency)
duration
start date
end date
notes:

**Comment by farmproject** [comment]
the Graphic User Interface need to have the display box or input box for the following
policy issuer for patience screen
policy status for patience screen

**Comment by sellnat77** [comment]
Action verbs for database relationships
- Patient visits doctor
- Doctor adds patient
- Patient visits pharmacy
- Doctor removes patient
- Doctor modifies patient 
- Pharmacy views patient
- Pharmacy views prescriptions
- Doctor views insurance

**Comment by sellnat77** [comment]
Database established and relationships are solidified, just need to connect gwt to database
